import json
import re
from datetime import date, timedelta

from playwright.sync_api import TimeoutError as PlaywrightTimeoutError
from playwright.sync_api import expect, sync_playwright


BASE_URL = "http://127.0.0.1:8000"
ADMIN_USERNAME = "testadmin"
ADMIN_PASSWORD = "TestPass123!"


class CheckRunner:
    def __init__(self):
        self.failures = []

    def check(self, name, condition, details=""):
        if condition:
            print(f"[PASS] {name}")
            return
        message = f"[FAIL] {name}"
        if details:
            message += f" :: {details}"
        print(message)
        self.failures.append(message)


def ensure_text(page, selector, text, timeout=10000):
    try:
        expect(page.locator(selector)).to_contain_text(text, timeout=timeout)
        return True
    except Exception:
        return False


def main():
    checks = CheckRunner()

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        context = browser.new_context()
        page = context.new_page()

        # Smoke test all major GET pages.
        routes = [
            "/",
            "/ssi/",
            "/ssi/verify/",
            "/ssi/create/",
            "/services/match/",
            "/zk/proof/",
            "/services/request/",
            "/eligibility/verify/",
            "/api/docs/",
            "/accounts/login/",
            "/admin/login/",
        ]

        for route in routes:
            response = page.goto(f"{BASE_URL}{route}", wait_until="domcontentloaded")
            checks.check(f"GET {route}", response is not None and response.ok, f"status={response.status if response else 'n/a'}")

        # API docs should render HTML (not raw JSON blob as default view).
        page.goto(f"{BASE_URL}/api/docs/", wait_until="domcontentloaded")
        checks.check("API docs HTML title", ensure_text(page, "h1", "CertifyChain SSI API v2.0"))
        checks.check("API docs has endpoint table", page.locator("table tbody tr").count() >= 4)

        # JSON mode must still be available for API clients.
        json_response = context.request.get(f"{BASE_URL}/api/docs/?format=json")
        data = json_response.json()
        checks.check("API docs JSON mode", json_response.ok and data.get("title") == "CertifyChain SSI API v2.0")

        # Login
        page.goto(f"{BASE_URL}/accounts/login/", wait_until="domcontentloaded")
        page.fill('input[name="username"]', ADMIN_USERNAME)
        page.fill('input[name="password"]', ADMIN_PASSWORD)
        page.click('button[type="submit"]')

        try:
            page.wait_for_url(re.compile(r".*/certificates/generate/.*"), timeout=10000)
            checks.check("Login redirect", True)
        except PlaywrightTimeoutError:
            checks.check("Login redirect", False, "Did not redirect to /certificates/generate/")
            page.goto(f"{BASE_URL}/certificates/generate/")

        # Issue a certificate through the browser form.
        today = date.today()
        valid_until = today + timedelta(days=365)

        page.fill("#recipient_address", "0x" + "1" * 40)
        page.fill("#refugee_name", "E2E User")
        page.fill("#transaction_hash", "0x" + "b" * 64)
        page.fill("#country", "CountryE2E")
        page.fill("#date_of_birth", "1997-01-01")
        page.fill("#address", "E2E Street")
        page.select_option("#gender", "female")
        page.fill("#skills", "communication,analysis")
        page.select_option("#employment_status", "unemployed")
        page.fill("#family_size", "3")
        page.select_option("#language_proficiency", "3")
        page.fill("#time_since_arrival", "8")
        page.fill("#issuing_date", today.isoformat())
        page.fill("#valid_until", valid_until.isoformat())
        page.fill("#certificate_data", "Generated by Playwright e2e")
        page.click('button[type="submit"]')

        checks.check("Certificate confirmation page", ensure_text(page, "h2", "Certificate Generated Successfully"))

        body_text = page.text_content("body") or ""
        match = re.search(r"Certificate ID:\s*(REF-[A-Z0-9]{3}-\d+)", body_text)
        certificate_id = match.group(1) if match else ""
        checks.check("Extract certificate ID", bool(certificate_id), body_text[:200])

        # Full SSI flow using the new certificate.
        page.goto(f"{BASE_URL}/ssi/verify/", wait_until="domcontentloaded")
        page.fill('input[name="certificate_id"]', certificate_id)
        page.click('button[type="submit"]')
        checks.check("Verify certificate flow", ensure_text(page, "#result", "Certificate Verified"))

        create_btn = page.locator("button", has_text="Create DID")
        if create_btn.count() > 0:
            create_btn.click()
            checks.check("Create DID from verify step", ensure_text(page, "#result", "DID"))

        page.goto(f"{BASE_URL}/ssi/create/?certificate_id={certificate_id}", wait_until="domcontentloaded")
        page.click('#identityForm button[type="submit"]')
        did_ok = ensure_text(page, "#result", "DID Ready") or ensure_text(page, "#result", "already have a DID")
        checks.check("Create identity page", did_ok)

        page.goto(f"{BASE_URL}/services/match/?certificate_id={certificate_id}", wait_until="domcontentloaded")
        page.click('#matchingForm button[type="submit"]')
        checks.check("Service matching", ensure_text(page, "#results", "services matched for", timeout=20000))

        page.goto(f"{BASE_URL}/zk/proof/?certificate_id={certificate_id}", wait_until="domcontentloaded")
        page.select_option('select[name="service_type"]', "healthcare")
        page.click('#zkForm button[type="submit"]')
        checks.check("Generate ZK proof", ensure_text(page, "#zkResult", "ZK proof generated successfully", timeout=20000))

        proof_json = '{"zk_proof":{"public_signals":["healthcare",50,1]}}'
        pre_count = page.locator("#zkResult pre").count()
        if pre_count > 0:
            raw_text = page.locator("#zkResult pre").first.text_content() or ""
            try:
                parsed = json.loads(raw_text)
                proof_json = json.dumps(parsed)
            except Exception:
                pass

        page.goto(f"{BASE_URL}/services/request/?certificate_id={certificate_id}&service_type=healthcare", wait_until="domcontentloaded")
        page.click('#requestForm button[type="submit"]')
        checks.check("Service request", ensure_text(page, "#requestResult", "Service request created", timeout=20000))

        page.goto(f"{BASE_URL}/eligibility/verify/", wait_until="domcontentloaded")
        page.fill("#proofJson", proof_json)
        page.click('#verifyEligibilityForm button[type="submit"]')
        checks.check("Eligibility verification", ensure_text(page, "#verifyResult", "access granted", timeout=20000))

        browser.close()

    if checks.failures:
        print("\nE2E RESULT: FAILED")
        for failure in checks.failures:
            print(failure)
        raise SystemExit(1)

    print("\nE2E RESULT: PASSED")


if __name__ == "__main__":
    main()
