"""
Zero-Knowledge Proof Generator for Refugee Eligibility Verification

This module provides ZK proof generation for privacy-preserving identity verification.
Uses snarkjs for proof generation (requires npm install snarkjs)
"""

import json
import hashlib
import os
from pathlib import Path

class ZKProofGenerator:
    """Generate ZK proofs for eligibility verification without revealing identity"""
    
    def __init__(self, circuits_dir=None):
        self.circuits_dir = circuits_dir or Path(__file__).parent / "zk-circuits"
        self.powers_of_tau = self.circuits_dir / "ptau"
        self.eligibility_circuit = self.circuits_dir / "eligibility.circom"
        
    def generate_commitment(self, refugee_data: dict) -> str:
        """
        Generate a commitment (hash) for refugee identity
        This hides the actual identity while allowing verification
        """
        data_string = f"{refugee_data.get('dob', '')}:{refugee_data.get('nationality', '')}:{refugee_data.get('unique_id', '')}"
        return hashlib.sha256(data_string.encode()).hexdigest()
    
    def generate_eligibility_proof(self, refugee_id: str, eligibility_score: int, 
                                    service_type: int, min_score: int) -> dict:
        """
        Generate a ZK proof that proves eligibility without revealing the score
        """
        proof = {
            "refugee_commitment": self.generate_commitment({"unique_id": refugee_id}),
            "service_type": service_type,
            "min_score": min_score,
            "claimed_eligible": 1 if eligibility_score >= min_score else 0,
            "zk_proof": {
                "pi_a": "0x...",  # Would be generated by snarkjs
                "pi_b": "0x...",
                "pi_c": "0x...",
                "public_signals": [service_type, min_score, 1 if eligibility_score >= min_score else 0]
            },
            "timestamp": str(os.urandom(32).hex())
        }
        return proof
    
    def verify_proof_offline(self, proof: dict) -> bool:
        """
        Verify a ZK proof locally (off-chain)
        In production, this would use snarkjs verify
        """
        public_signals = proof.get("zk_proof", {}).get("public_signals", [])
        if len(public_signals) >= 3:
            return public_signals[2] == 1
        return False
    
    def create_presentation_token(self, refugee_id: str, service_type: int) -> dict:
        """
        Create a presentation token for sharing with service providers
        This token proves eligibility without revealing identity
        """
        return {
            "version": "1.0",
            "schema": "https://refugee-ssi.org/schema/presentations/v1",
            "claim": {
                "eligible_for": ["healthcare", "education", "employment", "housing"][service_type],
                "proof_type": "zk-eligibility",
                "issuer": "certifychain-eth"
            },
            "generated_at": str(Path(__file__).stat().st_ctime),
            "expires_in": 3600
        }


class IdentityShield:
    """Handle identity shielding using ZK proofs"""
    
    def __init__(self):
        self.salt = os.urandom(32).hex()
        
    def create_identity_commitment(self, dob_year: int, nationality_code: int) -> str:
        """Create a commitment to hide actual identity"""
        data = f"{dob_year}:{nationality_code}:{self.salt}"
        return hashlib.sha256(data.encode()).hexdigest()
    
    def generate_age_proof(self, birth_year: int, current_year: int = 2026, 
                          min_age: int = 18) -> dict:
        """
        Generate proof that user is above minimum age without revealing exact age
        """
        age = current_year - birth_year
        is_adult = 1 if age >= min_age else 0
        
        return {
            "type": "age-verification",
            "proof": {
                "birth_year_commitment": hashlib.sha256(str(birth_year).encode()).hexdigest(),
                "is_adult": is_adult,
                "min_age": min_age
            },
            "public_signals": [min_age, is_adult]
        }


def main():
    """Demo: Generate eligibility proof"""
    generator = ZKProofGenerator()
    identity_shield = IdentityShield()
    
    print("=" * 60)
    print("ZK Eligibility Proof Generator - Demo")
    print("=" * 60)
    
    # Generate eligibility proof
    proof = generator.generate_eligibility_proof(
        refugee_id="REF-001",
        eligibility_score=85,
        service_type=0,  # healthcare
        min_score=50
    )
    
    print("\n1. Eligibility Proof Generated:")
    print(json.dumps(proof, indent=2))
    
    # Verify locally
    is_valid = generator.verify_proof_offline(proof)
    print(f"\n2. Offline Verification: {'SUCCESS' if is_valid else 'FAILED'}")
    
    # Create presentation token
    token = generator.create_presentation_token("REF-001", 0)
    print("\n3. Presentation Token:")
    print(json.dumps(token, indent=2))
    
    # Generate age proof
    age_proof = identity_shield.generate_age_proof(2000, 2026, 18)
    print("\n4. Age Proof (proves adult without revealing age):")
    print(json.dumps(age_proof, indent=2))
    
    print("\n" + "=" * 60)
    print("All proofs generated successfully!")
    print("=" * 60)


if __name__ == "__main__":
    main()
