# Generated by Django 6.0.3 on 2026-04-07 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefugeeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("did", models.CharField(max_length=100, unique=True)),
                ("eth_address", models.CharField(max_length=42)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("interested_healthcare", models.BooleanField(default=True)),
                ("interested_education", models.BooleanField(default=False)),
                ("interested_employment", models.BooleanField(default=False)),
                ("interested_housing", models.BooleanField(default=False)),
                (
                    "certificate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ssi_profile",
                        to="certificates.certificate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceEligibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_name", models.CharField(max_length=100)),
                ("service_type", models.CharField(max_length=50)),
                ("eligibility_score", models.IntegerField()),
                ("documents_required", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "refugee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eligibilities",
                        to="certificates.refugeeprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ZKProofRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_type", models.CharField(max_length=50)),
                ("commitment_hash", models.CharField(max_length=100)),
                ("proof_data", models.JSONField()),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("is_verified", models.BooleanField(default=True)),
                (
                    "refugee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zk_proofs",
                        to="certificates.refugeeprofile",
                    ),
                ),
            ],
        ),
    ]
