# Generated by Django 6.0.3 on 2026-04-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0002_refugeeprofile_serviceeligibility_zkproofrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="employment_status",
            field=models.CharField(
                choices=[
                    ("unemployed", "Unemployed"),
                    ("employed", "Employed"),
                    ("self_employed", "Self-Employed"),
                    ("student", "Student"),
                ],
                default="unemployed",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="family_size",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="certificate",
            name="has_children",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="certificate",
            name="language_proficiency",
            field=models.IntegerField(
                choices=[
                    (1, "None/Basic"),
                    (2, "Elementary"),
                    (3, "Intermediate"),
                    (4, "Advanced"),
                    (5, "Fluent"),
                ],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="skills",
            field=models.TextField(blank=True, help_text="Comma-separated skills"),
        ),
        migrations.AddField(
            model_name="certificate",
            name="special_needs",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="certificate",
            name="time_since_arrival",
            field=models.IntegerField(default=1, help_text="Months since arrival"),
        ),
    ]
