# Generated by Django 6.0.3 on 2026-04-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0003_certificate_employment_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="transaction_hash",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
